name: Build firmware FG‑4GT‑2SX_V2.0
on:
  push:
    branches: ['**']
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          apt update
          apt install make gcc sdcc xxd python-is-python3 libjson-c-dev zlib1g-dev -y

      - name: Run the host‑side unit tests
        run: make -C test

      - name: Check if machine.c can be compiled for all machines
        run: make machine_check

      - name: Build main firmware FG‑4GT‑2SX_V2.0
        run: make clean && make CI=1 MACHINE="FG-4GT-2SX_V2.0"

      - name: Build installer firmware FG‑4GT‑2SX_V2.0
        run: cd installer && make clean && make CI=1 MACHINE="FG-4GT-2SX_V2.0"

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RTLPlayground-FG‑4GT‑2SX_V2.0
          path: |
            *.hex
            *.bin
            installer/*.hex
            installer/*.bin

